name: taskdam
description: Horario, tareas, examenes y recordatorios para 2o DAM.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.5.1
  firebase_core: ^3.15.2
  intl: ^0.20.3
  google_sign_in: ^6.3.0
  http: ^1.6.0
  firebase_ui_oauth_google: ^1.4.3
  shared_preferences: ^2.5.5

dev_dependencies:
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - icons/icon-192.png

flutter_launcher_icons:
  android: true
  image_path: icons/icon-192.png