// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-ujXHr4mOCGGY9ZjsOR6-Z1v4UcqfnM',
    appId: '1:470468226376:web:f4769a3e55db273145d77d',
    messagingSenderId: '470468226376',
    projectId: 'horario-eba89',
    authDomain: 'horario-eba89.firebaseapp.com',
    storageBucket: 'horario-eba89.firebasestorage.app',
    measurementId: 'G-8M8WYB2QDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPbOfRgpR5zxaehvNLwfOwpKPBEaozkg',
    appId: '1:470468226376:android:b5f048fb911185a445d77d',
    messagingSenderId: '470468226376',
    projectId: 'horario-eba89',
    storageBucket: 'horario-eba89.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ts8kfFnKcvhM3mwk22dOnmHa8_pwRcE',
    appId: '1:470468226376:ios:876f8893b802be8145d77d',
    messagingSenderId: '470468226376',
    projectId: 'horario-eba89',
    storageBucket: 'horario-eba89.firebasestorage.app',
    androidClientId: '470468226376-65rfobu9erp2lml5jl97lr9eip814uru.apps.googleusercontent.com',
    iosClientId: '470468226376-af81m2i0qab1ml0kntqs0hu71scgubnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskdam',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ts8kfFnKcvhM3mwk22dOnmHa8_pwRcE',
    appId: '1:470468226376:ios:876f8893b802be8145d77d',
    messagingSenderId: '470468226376',
    projectId: 'horario-eba89',
    storageBucket: 'horario-eba89.firebasestorage.app',
    androidClientId: '470468226376-65rfobu9erp2lml5jl97lr9eip814uru.apps.googleusercontent.com',
    iosClientId: '470468226376-af81m2i0qab1ml0kntqs0hu71scgubnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskdam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-ujXHr4mOCGGY9ZjsOR6-Z1v4UcqfnM',
    appId: '1:470468226376:web:ac3704d329c72dbb45d77d',
    messagingSenderId: '470468226376',
    projectId: 'horario-eba89',
    authDomain: 'horario-eba89.firebaseapp.com',
    storageBucket: 'horario-eba89.firebasestorage.app',
    measurementId: 'G-ZCM6K3FYKM',
  );
}
