name: Generar APK de TaskDAM

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
  workflow_dispatch: # Mantiene la opción de ejecutarlo a mano

jobs:
  build-android:
    # Solo se ejecuta si el despliegue previo fue un éxito o si lo lanzas a mano
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Generar paquete APK desde PWA
        uses: pwa-builder/pwa-action@v1
        with:
          manifest-url: 'https://dev-trianald.github.io/horario/manifest.webmanifest'

      - name: Guardar APK como artefacto descargable
        uses: actions/upload-artifact@v4
        with:
          name: TaskDAM-APK
          path: '**/*.apk'